### PR TITLE
Remove Order FK + relation from Booking model and migration

### PR DESCRIPTION
**Pull request by kylebarney**
See pdbreen's comment on https://github.com/tipoff/bookings/pull/94

### CODE REVIEW

**Comment by pdbreen** [comment]
https://github.com/tipoff/bookings/pull/95

**Review by pdbreen — COMMENTED** [review]
.

**Comment by kylebarney** [comment]
Well, flip - @drewroberts is #95 ready to merge? The issue it resolves is blocking progress.

**Review by joshtorres — COMMENTED** [review]
I read through the issue and solution and this looks good to me

**Pull request closed without merging**
