### PR TITLE
Move Slot model and dependencies to Booking package

### PR DESCRIPTION
**Pull request by wolfrednicolas**

### CODE REVIEW

**Comment by wolfrednicolas** [comment]
Before merge this PR, its necessary

1- create a new version of support package with the changes in the model `SLOT`

**Comment by wolfrednicolas** [comment]
Hey @drewroberts after check the test, I realize that the SlotFactory may have an error in the definition.
when creating `$schedule = randomOrCreate(app('recurring_schedule'));`

the class`Tipoff\Scheduling\Models\RecurringSchedule`, has a field require called `valid_from`, we can check it in the migration `recurring_schedules`.

However in the test when creating the object `$schedule = randomOrCreate(app('recurring_schedule'));`

the log is `{"updated_at":"2021-02-21T16:55:13.000000Z","created_at":"2021-02-21T16:55:13.000000Z","id":1}`

so `$initialDate = $schedule->valid_from;` is empty

and `$initialDate->addDays(1);` empty of null throws an error

**Comment by drewroberts** [comment]
@wolfrednicolas That shouldn't matter since in the saving method of the model, it creates the valid_from field:

``` php
        static::saving(function ($schedule) {
            if (empty($schedule->valid_from)) {
                $schedule->valid_from = Carbon::today();
            }
        });
```

https://github.com/tipoff/scheduling/blob/main/src/Models/RecurringSchedule.php

**Comment by wolfrednicolas** [comment]
@drewroberts good to know that, however before save doesnt have the value, so maybe in the factory I can put the validation in order to avoid the issue
        if (empty($schedule->valid_from)) {
            $schedule->valid_from = Carbon::today();
        }

if I put these lines, the issue is fixed, however receive another error

Call to undefined method Tipoff\Scheduling\Models\RecurringSchedule::matchDate()

but the method RecurringSchedule has the matchDate function.

I dont know if I missing something

**Comment by drewroberts** [comment]
It might be because we renamed the scheduling package to tipoff/scheduler so you'll need to update that namespace

**Comment by wolfrednicolas** [comment]
@drewroberts I sent a PR to tipoff/support in order to have a new version with the scheduler name updated and then change here the version in the composer.json to test the package.

**Review by drewroberts — APPROVED** [review]
Thank you! 🚡

**Pull request merged**
