### PR TITLE
add participant and slot permissions to migration

### LINKED ISSUE #43: Permissions
Create Permissions (https://github.com/tipoff/authorization/issues/22) & assign to default Roles (https://github.com/tipoff/authorization/issues/21) using the new `PermissionMigration` and Helper in tipoff/authorization package:

- https://github.com/tipoff/authorization/issues/23

### PR DESCRIPTION
**Pull request by arwaawan3**
Closes #43

### CODE REVIEW

**Comment by drewroberts** [comment]
I'm going to hold off merging this until PR #47 is migrated and we know exactly what models & permissions are going to be in this pacakge.

**Comment by drewroberts** [comment]
I'm going to hold off merging this until PR #47 is migrated and we know exactly what models & permissions are going to be in this package.

**Comment by chx2** [comment]
Adding participant policy to #47

**Comment by arwaawan3** [comment]
Closes #43 Closes #53

**Review by drewroberts — APPROVED** [review]
Thank you! 🇺🇸

**Pull request merged**
